import PropTypes from "prop-types";

export const TEXT = PropTypes.shape({
                                        general: PropTypes.shape({
                                                                     tabUser: PropTypes.string.isRequired,
                                                                     tabProducts: PropTypes.string.isRequired,
                                                                     tabDishes: PropTypes.string.isRequired,
                                                                     tabLogout: PropTypes.string.isRequired,
                                                                     tabEditMode: PropTypes.string.isRequired
                                                                 }).isRequired,
                                        calculator: PropTypes.shape({
                                                                        age: PropTypes.string.isRequired,
                                                                        height: PropTypes.string.isRequired,
                                                                        weight: PropTypes.string.isRequired,
                                                                        gender: PropTypes.string.isRequired,
                                                                        genderMale: PropTypes.string.isRequired,
                                                                        genderFemale: PropTypes.string.isRequired,
                                                                        activity: PropTypes.string.isRequired,
                                                                        formula: PropTypes.string.isRequired,
                                                                        benedict: PropTypes.string.isRequired,
                                                                        mifflin: PropTypes.string.isRequired,
                                                                        low: PropTypes.string.isRequired,
                                                                        medium: PropTypes.string.isRequired,
                                                                        high: PropTypes.string.isRequired,
                                                                        very_high: PropTypes.string.isRequired,
                                                                        buttonCalculate: PropTypes.string.isRequired,
                                                                        modalHeaderCalculate: PropTypes.string.isRequired,
                                                                        modalResultText: PropTypes.string.isRequired,
                                                                        modalButtonCancel: PropTypes.string.isRequired
                                                                    }).isRequired,
                                        products: PropTypes.shape({
                                                                      buttonCreate: PropTypes.string.isRequired,
                                                                      buttonProductTypes: PropTypes.string.isRequired,
                                                                      buttonLoadCsv: PropTypes.string.isRequired,
                                                                      buttonEdit: PropTypes.string.isRequired,
                                                                      buttonDelete: PropTypes.string.isRequired,
                                                                      inputRecordsNumber: PropTypes.string.isRequired,
                                                                      selectType: PropTypes.string.isRequired,
                                                                      tableHeadName: PropTypes.string.isRequired,
                                                                      tableHeadEnergy: PropTypes.string.isRequired,
                                                                      tableHeadType: PropTypes.string.isRequired,
                                                                      tableHeadActions: PropTypes.string.isRequired,
                                                                      modalEditProductHeadCreate: PropTypes.string.isRequired,
                                                                      modalEditProductHeadEdit: PropTypes.string.isRequired,
                                                                      modalEditProductInputName: PropTypes.string.isRequired,
                                                                      modalEditProductInputEnergy: PropTypes.string.isRequired,
                                                                      modalEditProductSelectType: PropTypes.string.isRequired,
                                                                      modalEditProductButtonCancel: PropTypes.string.isRequired,
                                                                      modalEditTypeHeader: PropTypes.string.isRequired,
                                                                      modalEditTypeButtonCancel: PropTypes.string.isRequired,
                                                                      modalEditTypeInputName: PropTypes.string.isRequired,
                                                                      modalEditTypeButtonCreate: PropTypes.string.isRequired,
                                                                      modalEditTypeButtonSave: PropTypes.string.isRequired,
                                                                      modalEditTypeTableHeadName: PropTypes.string.isRequired,
                                                                      modalEditTypeTableHeadEdit: PropTypes.string.isRequired,
                                                                      modalEditTypeTableHeadDelete: PropTypes.string.isRequired
                                                                  }).isRequired,
                                        dishes: PropTypes.shape({
                                                                    buttonCreate: PropTypes.string.isRequired,
                                                                    tableHeadName: PropTypes.string.isRequired,
                                                                    tableHeadEnergy: PropTypes.string.isRequired,
                                                                    tableHeadAmount: PropTypes.string.isRequired,
                                                                    buttonEdit: PropTypes.string.isRequired,
                                                                    buttonDelete: PropTypes.string.isRequired,
                                                                    modalEditHeader: PropTypes.string.isRequired,
                                                                    modalEditTotalEnergyText: PropTypes.string.isRequired,
                                                                    modalEditInputProductName: PropTypes.string.isRequired,
                                                                    modalEditTableHeaderName: PropTypes.string.isRequired,
                                                                    modalEditTableHeaderEnergy: PropTypes.string.isRequired,
                                                                    modalEditTableHeaderAmount: PropTypes.string.isRequired,
                                                                    modalEditTableHeaderDelete: PropTypes.string.isRequired,
                                                                    modalEditTableInputAmount: PropTypes.string.isRequired,
                                                                    modalEditButtonCancel: PropTypes.string.isRequired,
                                                                    modalEditButtonSave: PropTypes.string.isRequired
                                                                }).isRequired
                                    });